import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://emis-staging.tnsed.com/auth/login?returnUrl=%2Fdashboard');
  await page.getByRole('img').nth(1).click();
  await page.getByText('Educational Management').click();
  await page.getByText('User Name').click();
  await page.getByRole('textbox', { name: 'UserName' }).click();
  await page.getByText('Password', { exact: true }).click();
  await page.getByRole('textbox', { name: 'Password *' }).click();
  await page.getByRole('textbox', { name: 'UserName' }).click();
  await page.getByRole('textbox', { name: 'UserName' }).fill('         ');
  await page.getByRole('textbox', { name: 'Password *' }).click();
  await page.getByRole('textbox', { name: 'Password *' }).fill('test@123');
  await page.getByRole('textbox', { name: 'Password *' }).click();
  await page.locator('i').click();
  await page.locator('i').click();
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByRole('textbox', { name: 'UserName' }).click();
  await page.getByRole('textbox', { name: 'UserName' }).fill('4028609');
  await page.getByRole('textbox', { name: 'Password *' }).click();
  await page.getByRole('textbox', { name: 'Password *' }).fill('          ');
  await page.locator('i').click();
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByRole('textbox', { name: 'UserName' }).click();
  await page.getByRole('textbox', { name: 'UserName' }).fill('jjfdgfuihgfgufgfufe');
  await page.getByRole('textbox', { name: 'Password *' }).click();
  await page.getByRole('textbox', { name: 'Password *' }).fill('test@123');
  await page.locator('i').click();
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByRole('textbox', { name: 'UserName' }).click();
  await page.getByRole('button', { name: 'Forgot Password' }).click();
  await page.getByText('UserType').click();
  await page.getByText('Please Select Your User Type').click();
  await page.getByText('UserType', { exact: true }).click();
  await page.getByText('School', { exact: true }).click();
  await page.getByRole('button', { name: 'dropdown trigger' }).click();
  await page.getByText('Teacher').click();
  await page.getByText('User Name').click();
  await page.getByRole('textbox', { name: 'UserName' }).click();
  await page.getByRole('textbox', { name: 'UserName' }).fill('kkbdkvdkvhkhdhv');
  await page.getByRole('button', { name: 'Request OTP' }).click();
  await page.getByRole('button', { name: 'Request OTP' }).click();
  await page.getByRole('textbox', { name: 'UserName' }).click();
  await page.getByRole('textbox', { name: 'UserName' }).fill('');
  await page.getByRole('textbox', { name: 'UserName' }).press('Enter');
  await page.getByRole('textbox', { name: 'UserName' }).fill('5646545456');
  await page.getByRole('button', { name: 'Request OTP' }).click();
  await page.getByRole('textbox', { name: 'UserName' }).click();
  await page.getByRole('textbox', { name: 'UserName' }).fill('                          ');
  await page.getByRole('button', { name: 'Request OTP' }).click();
  await page.getByRole('button', { name: 'Request OTP' }).click();
  await page.getByRole('textbox', { name: 'UserName' }).click();
  await page.getByRole('textbox', { name: 'UserName' }).fill('4028609');
  await page.getByRole('button', { name: 'Request OTP' }).click();
  await page.getByRole('textbox', { name: 'UserName' }).click();
  await page.getByRole('textbox', { name: 'UserName' }).fill('33020700907');
  await page.getByRole('button', { name: 'OTP Submit' }).click();
  await page.getByRole('button', { name: 'OTP Submit' }).dblclick();
  await page.getByRole('button', { name: 'OTP Submit' }).click();
  await page.getByRole('button', { name: 'Request OTP' }).click();
  await page.getByRole('button', { name: 'Request OTP' }).click();
  await page.getByRole('button', { name: 'Request OTP' }).click();
  await page.getByRole('textbox', { name: 'UserName' }).click();
  await page.getByRole('button', { name: 'Request OTP' }).click();
  await page.getByRole('textbox', { name: 'UserName' }).click();
  await page.getByRole('textbox', { name: 'UserName' }).fill('33020700907');
  await page.getByRole('textbox', { name: 'UserName' }).click();
  await page.getByRole('textbox', { name: 'UserName' }).fill('42086091');
  await page.getByRole('button', { name: 'Request OTP' }).click();
  await page.getByRole('textbox', { name: 'UserName' }).click();
  await page.getByRole('textbox', { name: 'UserName' }).fill('4208609');
  await page.getByRole('textbox', { name: 'UserName' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'UserName' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'UserName' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'UserName' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'UserName' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'UserName' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'UserName' }).fill(' 4208609');
});